spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ""
    password: ""
    url: "
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
      use-new-id-generator-mappings: true
    show-sql: true
    open-in-view: true
    generate-ddl: true